import AuthLayoutNav from "@/components/Navbar/AuthLayoutNav/AuthLayoutNav";

// export const metadata = {
//   title: "",
//   description: "Generated by create next app",
// };
const AuthLayout = ({ children }) => {
  return (
    <>
      <AuthLayoutNav />
      {children}
    </>
  );
};

export default AuthLayout;
