import MainNav from "@/components/Navbar/MainNav";
import font from "./font";
import "./globals.css";
import Footer from "@/components/Shared/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function conbineFontVariable(font) {
  let fontVariable = "";
  for (const key in font) {
    fontVariable += `${font[key].variable} `;
  }
  return fontVariable;
}
export default function RootLayout({ children }) {
  // ${font.caustenFontReguler.variable} ${font.caustenFontBold.variable} ${font.coreSansFontReguler.variable}
  return (
    <html lang="en">
      <body className={`${conbineFontVariable(font)}  bg-white`}>
        <MainNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
