FROM node:22-alpine

WORKDIR /app

ARG NODE_ENV
ARG APP_PORT

RUN corepack enable && \
    corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE ${APP_PORT}

CMD ["pnpm", "start:dev"]