name: CI

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  lint-typecheck-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm lint

      - name: Type check code
        run: pnpm typecheck

      - name: Build code
        run: pnpm build
